[app]
mode = stdout
; mode = db
; mode = server

[api]
url = https://api.osv.dev/v1/query

[server]
host = 127.0.0.1
port = 8080

[db]
driver = csv
path = ./packages.csv
; driver = sqlite3
; path = ./packages.sqlite3
