[scraper]
start_url = https://books.toscrape.com/catalogue/page-1.html
base_url = https://books.toscrape.com/catalogue/
; nombre de pages à parcourir (50 pages disponibles au total)
max_pages = 5
timeout = 10

[output]
path = ./books.csv
